//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemek_Poşeti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public string CName { get; set; }
        public string CUserName { get; set; }
        public string CUserPassword { get; set; }
        public string CUserMail { get; set; }
        public string CUserAddress { get; set; }
    }
}
